export const INDEX_STRATEGY = {
  users: ['ux_users_email_active (email, deleted_at)', 'ix_users_role_active (role_id, is_active, deleted_at)'],
  roles: ['ux_roles_key_active (key, deleted_at)', 'ix_roles_sort (sort_order, deleted_at)'],
  permissions: ['ux_permissions_key_active (key, deleted_at)', 'ix_permissions_module (module, deleted_at)'],
  categories: ['ux_categories_slug_active (slug, deleted_at)', 'ix_categories_parent (parent_category_id, sort_order, deleted_at)'],
  brands: ['ux_brands_slug_active (slug, deleted_at)', 'ix_brands_name (name, deleted_at)'],
  products: ['ux_products_slug_active (slug, deleted_at)', 'ix_products_brand_category (brand_id, category_id, deleted_at)', 'ix_products_canonical (canonical_product_id, deleted_at)'],
  product_specifications: ['ix_product_specs_product_sort (product_id, sort_order, deleted_at)', 'ix_product_specs_key (spec_key, spec_value_normalized, deleted_at)'],
  stores: ['ux_stores_slug_active (slug, deleted_at)', 'ix_stores_active (is_active, deleted_at)'],
  store_products: ['ux_store_products_store_sku_active (store_id, external_sku, deleted_at)', 'ix_store_products_product (product_id, deleted_at)', 'ix_store_products_availability (availability, is_available, deleted_at)'],
  product_matching: ['ux_product_matching_source_target (source_store_product_id, canonical_product_id, deleted_at)', 'ix_product_matching_status (status, confidence_score, deleted_at)'],
  price_history: ['ix_price_history_store_product_time (store_product_id, recorded_at)', 'ix_price_history_product_time (product_id, recorded_at)', 'ix_price_history_price (product_id, current_price, recorded_at)'],
  wishlists: ['ix_wishlists_user_default (user_id, is_default, deleted_at)'],
  wishlist_items: ['ux_wishlist_items_wishlist_product (wishlist_id, product_id, deleted_at)', 'ix_wishlist_items_product (product_id, deleted_at)'],
  price_alerts: ['ix_price_alerts_user_active (user_id, is_active, deleted_at)', 'ix_price_alerts_product_target (product_id, target_price, is_active, deleted_at)'],
  notifications: ['ix_notifications_user_status (user_id, status, created_at)', 'ix_notifications_alert_channel (price_alert_id, channel, created_at)'],
  scraper_registry: ['ux_scraper_registry_store_key (store_id, scraper_key, deleted_at)', 'ix_scraper_registry_health (health_status, is_enabled, is_paused, deleted_at)'],
  scraper_configurations: ['ix_scraper_configurations_registry_version (scraper_registry_id, version, is_active, deleted_at)'],
  scraper_execution_logs: ['ix_scraper_execution_logs_registry_status (scraper_registry_id, status, started_at)', 'ix_scraper_execution_logs_finished (finished_at, status)'],
  audit_logs: ['ix_audit_logs_actor_time (actor_user_id, created_at)', 'ix_audit_logs_entity_time (entity_type, entity_id, created_at)', 'ix_audit_logs_action_status (action, status, created_at)'],
} as const;

export const FOREIGN_KEY_STRATEGY = [
  'users.role_id -> roles.id ON UPDATE CASCADE ON DELETE RESTRICT',
  'role_permissions.role_id -> roles.id ON UPDATE CASCADE ON DELETE CASCADE',
  'role_permissions.permission_id -> permissions.id ON UPDATE CASCADE ON DELETE CASCADE',
  'categories.parent_category_id -> categories.id ON UPDATE CASCADE ON DELETE SET NULL',
  'products.brand_id -> brands.id ON UPDATE CASCADE ON DELETE RESTRICT',
  'products.category_id -> categories.id ON UPDATE CASCADE ON DELETE RESTRICT',
  'products.canonical_product_id -> products.id ON UPDATE CASCADE ON DELETE SET NULL',
  'product_specifications.product_id -> products.id ON UPDATE CASCADE ON DELETE CASCADE',
  'store_products.store_id -> stores.id ON UPDATE CASCADE ON DELETE RESTRICT',
  'store_products.product_id -> products.id ON UPDATE CASCADE ON DELETE RESTRICT',
  'product_matching.source_store_product_id -> store_products.id ON UPDATE CASCADE ON DELETE CASCADE',
  'product_matching.canonical_product_id -> products.id ON UPDATE CASCADE ON DELETE RESTRICT',
  'price_history.store_product_id -> store_products.id ON UPDATE CASCADE ON DELETE CASCADE',
  'price_history.product_id -> products.id ON UPDATE CASCADE ON DELETE CASCADE',
  'wishlist_items.wishlist_id -> wishlists.id ON UPDATE CASCADE ON DELETE CASCADE',
  'wishlist_items.product_id -> products.id ON UPDATE CASCADE ON DELETE CASCADE',
  'price_alerts.user_id -> users.id ON UPDATE CASCADE ON DELETE CASCADE',
  'price_alerts.product_id -> products.id ON UPDATE CASCADE ON DELETE CASCADE',
  'notifications.user_id -> users.id ON UPDATE CASCADE ON DELETE CASCADE',
  'notifications.price_alert_id -> price_alerts.id ON UPDATE CASCADE ON DELETE SET NULL',
  'scraper_registry.store_id -> stores.id ON UPDATE CASCADE ON DELETE RESTRICT',
  'scraper_configurations.scraper_registry_id -> scraper_registry.id ON UPDATE CASCADE ON DELETE CASCADE',
  'scraper_execution_logs.scraper_registry_id -> scraper_registry.id ON UPDATE CASCADE ON DELETE CASCADE',
  'scraper_execution_logs.scraper_configuration_id -> scraper_configurations.id ON UPDATE CASCADE ON DELETE SET NULL',
  'audit_logs.actor_user_id -> users.id ON UPDATE CASCADE ON DELETE SET NULL',
  'audit_logs.actor_role_id -> roles.id ON UPDATE CASCADE ON DELETE SET NULL',
] as const;

export const QUERY_OPTIMIZATION_CONSIDERATIONS = [
  'All read queries should default to deleted_at IS NULL to preserve soft-delete semantics without losing historical rows.',
  'Catalog list pages should read from narrow covering indexes on slug, category, brand, active state, and deleted_at.',
  'Price history should be append-only and queried by store_product_id and recorded_at for fast timeline rendering.',
  'Comparison pages should read the current offer row first, then hydrate history lazily to avoid scanning history tables.',
  'Admin search and moderation flows should use pagination with keyset-style ordering where possible.',
  'JSON-heavy fields should be queried sparingly and indexed only through dedicated generated columns if required later.',
  'Write amplification should be controlled by keeping the current-state tables small and the history tables append-only.',
] as const;
